### ISSUE TITLE
Checkbox not working on iOS

### ISSUE THREAD

**Issue by Devon66h** [react-native-checkbox/react-native-checkbox#93]
Hey there, I am trying to implement this checkbox into my react native project. It works perfectly fine on Android but on iOS I get this issue: 

![image](https://user-images.githubusercontent.com/3513163/95907567-bc7d7d80-0d69-11eb-8f61-3ace31292bd9.png)

Is the checkbox not supported on iOS? Please let me know if you have a solution. Thanks.

**Comment by nicholaslee119** [comment]
Have you ever tried the `npx pod-install` ?

**Comment by Devon66h** [comment]
> Have you ever tried the `npx pod-install` ?

I am using Expo to build my react-native project, so I am unable to run `npx pod-install`

**Comment by Mapsimiliano** [comment]
Hi @Devon66h , 

I am facing the same issue, but I think it is because we are trying to access a native component but we are using Expo, so in iOS is using a native component and it is not exposed to the JS layer from Expo. 

This link might help you to understand what is the problem:
https://github.com/expo/expo/issues/6841

The solution for me is to look for another component based on JS and not in a native component like this one does.

Hope this is helpful for you

**Comment by Devon66h** [comment]
@Mapsimiliano Thank you for the information.

**Comment by LevelPanic** [comment]
I'm getting the same issue! Using Expo SDK 39 and React Native 0.63.3.

**Comment by Devon66h** [comment]
Decided to use [React Native Paper Checkbox](https://callstack.github.io/react-native-paper/checkbox.html) instead

**Comment by szabelin** [comment]
this isn't useful at all. Expo moved to use new checkbox, and it's not working. If Expo can't get this working, could at least suggest something better. I'll check Devon's suggestion

**Comment by codr36** [comment]
Same issue.

**Comment by howardwu1** [comment]
> this isn't useful at all. Expo moved to use new checkbox, and it's not working. If Expo can't get this working, could at least suggest something better. I'll check Devon's suggestion

Yeah I submitted a bug report for expo-checkbox. Hopefully that gets addressed. Also, IOS will not suport it, but at least the docs mention it
